---
- name: Enabling the required rpm repos
  command: yum-config-manager --enable rhel-server-rhscl-6-rpms

- name: Installing apache, required php version + extensions
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - httpd24
    - rh-php70-php-gd
    - rh-php70-php-pdo
    - rh-php70-php-mysqlnd
    - rh-php70-php-opcache
    - rh-php70-php-xml
    - rh-php70-php-cli
    - rh-php70-php-fpm

- name: configure apache to use php-fpm
  copy:
    src: fpm.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/fpm.conf

- name: Restart Webserver
  command: echo "this task will restart the web services"
  notify: "restart webserver"

- name: Get Drupal
  get_url:
    url: https://ftp.drupal.org/files/projects/drupal-8.3.7.tar.gz
    dest: /opt/rh/httpd24/root/var/www

- name: Unzip Drupal Archive
  unarchive:
    src: /opt/rh/httpd24/root/var/www/drupal-8.3.7.tar.gz
    dest: /opt/rh/httpd24/root/var/www/html
    extra_opts: [--strip-components=1]
    remote_src: True

- name: Create Drupal files directory
  file:
    path: /opt/rh/httpd24/root/var/www/html/sites/default/files
    state: directory
    owner: apache
    group: apache
    mode: 0775

- name: Create a settings file
  copy:
    src: /opt/rh/httpd24/root/var/www/html/sites/default/default.settings.php
    dest: /opt/rh/httpd24/root/var/www/html/sites/default/settings.php
    owner: apache
    group: apache
    mode: 0744
    remote_src: true
    force: no
    
- name: Enable clean URLs via AllowOverride All via httpd-d8.conf
  copy:
    src: httpd-d8.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/httpd-d8.conf