---
- name: Install required php extensions
  yum:
    name: php-gd
    state: installed
  yum:
    name: php-domxml-php4-php5
    state: installed
  yum:
    name: php-mysql
    state: installed
  notify:
    - restart httpd

- name: Get Drupal
  get_url:
    url: https://ftp.drupal.org/files/projects/drupal-7.56.tar.gz
    ## TODO: Add drupal 8 as var
    # url: https://ftp.drupal.org/files/projects/drupal-8.3.7.tar.gz
    dest: /var/www

- name: Unzip Drupal Archive
  unarchive:
    src: /var/www/drupal-7.56.tar.gz
    ## TODO: Add drupal 8 as var
    # src: /var/www/drupal-8.3.7.tar.gz
    dest: /var/www/html
    extra_opts: [--strip-components=1]
    remote_src: True
