---
# - name: Enabling the required rpm repos
#   yum_repository:
#     name: rhel-server-rhscl-6-rpms
#     baseurl:
  
- name: Installing apache, required php version + extensions
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    # - rh-httpd24-httpd
    - httpd24
    - rh-php70-php-cli
    - rh-php70-php-fpm
    # - php-gd
    
  # yum:
  #   name: php-domxml-php4-php5
  #   state: installed
  # yum:
  #   name: php-mysql
  #   state: installed
  
  notify:
    - restart php-fpm
  notify:
    - restart httpd

- name: Get Drupal
  get_url:
    # url: https://ftp.drupal.org/files/projects/drupal-7.56.tar.gz
    url: https://ftp.drupal.org/files/projects/drupal-8.3.7.tar.gz
    dest: /opt/rh/httpd24/root/var/www

- name: Unzip Drupal Archive
  unarchive:
    # src: /var/www/drupal-7.56.tar.gz
    src: /opt/rh/httpd24/root/var/www/drupal-8.3.7.tar.gz
    dest: /opt/rh/httpd24/root/var/www/html
    extra_opts: [--strip-components=1]
    remote_src: True
